# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcHo0e2aQezo4uYakeI83LZtHTZ96dFf
"""

import pandas as pd
boston_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
boston_df=pd.read_csv(boston_url)
boston_df

#Datasetning umumiy qator va ustunlar sonini 
num_rows, num_columns = boston_df.shape

#Birinchi 5 ta qatorni ko'rsating.
first_5_rows = boston_df.head(5)

#CRIM ustunining o'rtacha qiymatini 
average_crime_rate = boston_df['CRIM'].mean()

#MEDV ustunining eng yuqori qiymatini 
highest_median_value = boston_df['MEDV'].max()

#TAX ustunining eng kam qiymatini 
lowest_tax_rate = boston_df['TAX'].min()

#NOX ustunining standart deviasiyasini 
nox_std_dev = boston_df['NOX'].std()

#Barcha ustunlarning nomlarini chiqaring
column_names = boston_df.columns

#RAD ustunidagi qiymatlar bo'yicha ma'lumotlar sanasini hisoblash
rad_value_counts = boston_df['RAD'].value_counts()

#AGE ustunidagi ma'lumotlar medianasini hisoblash
age_median = boston_df['AGE'].median()

#PTRATIO ustunidagi ma'lumotlarning 25%, 50%, va 75% percentillarini hisobash
ptratio_percentiles = boston_df['PTRATIO'].describe(percentiles=[0.25, 0.5, 0.75])

#RM ustunidagi ma'lumotlar o'rtasini hisoblash
rm_mean = boston_df['RM'].mean()

#LSTAT ustunidagi ma'lumotlar o'rtacha qiymatini hisoblash
lstat_mean = boston_df['LSTAT'].mean()

#CHAS ustunida Charles daryosining chegarasiga tegishli hududlar sonini hisoblash (1-ga teng bo'lganlar).
chas_count = boston_df['CHAS'].sum()

# task 4
# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Boxplot for "Median value of owner-occupied homes":
plt.figure(figsize=(8, 6))
plt.boxplot(boston_df['MEDV'])
plt.xlabel('Homes')
plt.ylabel('Median Value ($1000s)')
plt.title('Boxplot of Median Value of Owner-Occupied Homes')
plt.show()

# Bar plot for the "Charles river" variable:
charles_river_counts = boston_df['CHAS'].value_counts()
plt.bar(charles_river_counts.index, charles_river_counts.values)
plt.xlabel('Charles River')
plt.ylabel('Frequency')
plt.title('Bar Plot of Charles River Variable')
plt.xticks([0, 1], ['Not Bound', 'Bound'])
plt.show()

# Boxplot for "Median value of owner-occupied homes" vs "AGE" variable:
age_groups = pd.cut(boston_df['AGE'], bins=[0, 35, 70, np.inf], labels=['35 years and younger', 'between 35 and 70 years', '70 years and older'])
plt.figure(figsize=(8, 6))
sns.boxplot(x=age_groups, y=boston_df['MEDV'])
plt.xlabel('Age Groups')
plt.ylabel('Median Value ($1000s)')
plt.title('Boxplot of Median Value of Owner-Occupied Homes by Age Group')
plt.show()

# Scatter plot for "Nitric oxide concentrations" vs "Proportion of non-retail business acres per town":
plt.figure(figsize=(8, 6))
plt.scatter(boston_df['NOX'], boston_df['INDUS'])
plt.xlabel('Nitric Oxide Concentrations (NOX)')
plt.ylabel('Proportion of Non-Retail Business Acres (INDUS)')
plt.title('Scatter Plot: NOX vs INDUS')
plt.show()

# Histogram for the "Pupil-Teacher Ratio" variable:
plt.figure(figsize=(8, 6))
plt.hist(boston_df['PTRATIO'], bins=10, edgecolor='black')
plt.xlabel('Pupil-Teacher Ratio (PTRATIO)')
plt.ylabel('Frequency')
plt.title('Histogram of Pupil-Teacher Ratio')
plt.show()

# task 6

import pandas as pd
import numpy as np
boston_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
boston_df = pd.read_csv(boston_url)

# 1- State the hypothesis:

# Null hypothesis (H0): There is no significant difference in the median value of houses bounded by the Charles river.
# Alternative hypothesis (HA): There is a significant difference in the median value of houses bounded by the Charles river.

#2- Perform the t-test for independent samples:
from scipy.stats import ttest_ind

charles_river_houses = boston_df[boston_df['CHAS'] == 1]['MEDV']
non_charles_river_houses = boston_df[boston_df['CHAS'] == 0]['MEDV']

t_statistic, p_value = ttest_ind(charles_river_houses, non_charles_river_houses)

alpha = 0.05

if p_value < alpha:
    conclusion = "Reject the null hypothesis. There is a significant difference in the median value of houses bounded by the Charles river."
else:
    conclusion = "Fail to reject the null hypothesis. There is no significant difference in the median value of houses bounded by the Charles river."

t_statistic
p_value
conclusion

# 3-State the hypothesis:

#Null hypothesis (H0): There is no difference in median values of houses (MEDV) for each proportion of owner-occupied units built prior to 1940 (AGE).
#Alternative hypothesis (HA): There is a difference in median values of houses (MEDV) for each proportion of owner-occupied units built prior to 1940 (AGE).

# 4- Perform ANOVA:

from scipy.stats import f_oneway

age_groups = pd.cut(boston_df['AGE'], bins=[0, 35, 70, np.inf], labels=['35 years and younger', 'between 35 and 70 years', '70 years and older'])

age_group_1 = boston_df[age_groups == '35 years and younger']['MEDV']
age_group_2 = boston_df[age_groups == 'between 35 and 70 years']['MEDV']
age_group_3 = boston_df[age_groups == '70 years and older']['MEDV']

f_statistic, p_value = f_oneway(age_group_1, age_group_2, age_group_3)

alpha = 0.05

if p_value < alpha:
    conclusion = "Reject the null hypothesis. There is a difference in median values of houses for each proportion of owner-occupied units built prior to 1940 (AGE)."
else:
    conclusion = "Fail to reject the null hypothesis. There is no difference in median values of houses for each proportion of owner-occupied units built prior to 1940 (AGE)."

f_statistic
p_value
conclusion

# 5-State the hypothesis:

#Null hypothesis (H0): There is no relationship between nitric oxide concentrations (NOX) and the proportion of non-retail business acres per town (INDUS).
#Alternative hypothesis (HA): There is a relationship between nitric oxide concentrations (NOX) and the proportion of non-retail business acres per town (INDUS).

# 6-Perform Pearson correlation:
from scipy.stats import pearsonr

correlation, p_value = pearsonr(boston_df['NOX'], boston_df['INDUS'])

alpha = 0.05

if p_value < alpha:
    conclusion = "Reject the null hypothesis. There is a significant relationship between nitric oxide concentrations and the proportion of non-retail business acres per town."
else:
    conclusion = "Fail to reject the null hypothesis. There is no significant relationship between nitric oxide concentrations and the proportion of non-retail business acres per town."

correlation
p_value
conclusion

#7- Perform regression analysis:
import statsmodels.api as sm

X = boston_df['DIS']
y = boston_df['MEDV']

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

model.summary()

